[package]
name = "mcts"
version = "0.1.0"
authors = ["flegac <florent@monkeypatch.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indextree = "4.3.1"