[package]
name = "go-game"
version = "0.1.0"
authors = ["Florent"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.go-lib]
path = "../go-lib"

[dependencies.mcts-lib]
path = "../mcts-lib"