[package]
name = "go-lib"
version = "0.1.0"
authors = ["Florent"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"

[dependencies.mcts-lib]
path = "../mcts-lib"
